serverConfig:
    ruleAddress:   "rule"
    ticketAddress: "ticket"
    port:          8080
SQLConfig:
    host:          "localhost"
    port:          5432
    username:      "postgres"
    password:      "Ah1381/10/27"
    dataBase:      "bootcamp"
    schema:        "private"
    ruleTable:     "rules"
    cityTable:     "cities"
    airlineTable:  "airlines"
    agencyTable:   "agencies"
    supplierTable: "suppliers"
redisConfig:
    address:       "192.168.220.128"
    port:          6379
    username:      ""
    password:      ""
    dataBase:      0
